name: 'dwh'
version: '1.0.0'
profile: 'dwh'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dwh:
    staging:
      +tags: staging
      +schema: staging
      +materialized: view

    intermediate:
      +tags: staging
      +schema: staging
      +materialized: view

    facts:
      +tags: core
      +schema: main
      +materialized: incremental

    dimensions:
      +tags: core
      +schema: main
      +materialized: table

    marts:
      +tags: serving
      +schema: marts
      +materialized: table          
    
    # old folder with sql metrics, use MetricFlow instead
    # metrics:
    #   +enabled: false
    #   +schema: marts
    #   +materialized: table

    semantic_models:
      +tags: serving
      +enabled: true
      +schema: main
      +materialized: table

    serving:
      marts:
      +tags: serving
      +schema: serving
      +materialized: table      
 
vars:
  start_date: '2005-01-01'
  end_date: '2008-01-01'
  default_date: '9999-12-31'
  default_date_key: 99991231

