version: 2

sources:
  - name: rental
    database: dwh
    schema: source
    tables:
      - name: rental
      - name: film
      - name: customer
      - name: payment
      - name: store
      - name: staff
      - name: inventory
      - name: address
      - name: city
      - name: country
      - name: language
