# snapshots:
#   - name: sna_customer
#     relation: ref('mid_customer')
#     config:
#       schema: dwh
#       database: dvdrental
#       unique_key: customer_id
#       strategy: keys
#       dbt_valid_to_current: "to_date('9999-12-31')" # Specifies that current records should have `dbt_valid_to` set to `'9999-12-31'` instead of `NULL`.