version: 2

models:
  - name: metric_daily_sales
    description: Daily sales metrics with rental and revenue aggregations
    columns:
      - name: date_day
        description: Calendar date
      - name: year
        description: Year
      - name: month
        description: Month number
      - name: total_rentals
        description: Count of rentals for the day
      - name: total_revenue
        description: Sum of revenue for the day
      - name: unique_customers
        description: Count of unique customers for the day
      - name: unique_films_rented
        description: Count of unique films rented
      - name: active_stores
        description: Count of stores with activity
      - name: average_rental_amount
        description: Average rental amount
      - name: min_rental_amount
        description: Minimum rental amount
      - name: max_rental_amount
        description: Maximum rental amount
        
  - name: metric_monthly_sales
    description: Monthly sales metrics with year-to-date calculations
    columns:
      - name: year
        description: Year
      - name: month
        description: Month number
      - name: month_start_date
        description: First day of the month
      - name: total_rentals
        description: Count of rentals for the month
      - name: total_revenue
        description: Sum of revenue for the month
      - name: unique_customers
        description: Count of unique customers for the month
      - name: unique_films_rented
        description: Count of unique films rented
      - name: average_rental_amount
        description: Average rental amount
      - name: revenue_ytd
        description: Year-to-date cumulative revenue
        
  - name: metric_customer_performance
    description: Customer performance metrics with segmentation
    columns:
      - name: customer_key
        description: Customer surrogate key
      - name: customer_id
        description: Customer business key
      - name: first_name
        description: First name
      - name: last_name
        description: Last name
      - name: email
        description: Email address
      - name: city
        description: City
      - name: country
        description: Country
      - name: is_active
        description: Active status
      - name: total_rentals
        description: Total number of rentals by customer
      - name: total_revenue
        description: Total revenue from customer
      - name: average_rental_value
        description: Average value per rental
      - name: first_rental_date_key
        description: Date key of first rental
      - name: last_rental_date_key
        description: Date key of most recent rental
      - name: customer_segment
        description: Segment (High/Medium/Low Value, No Activity)
      - name: revenue_quartile
        description: Revenue quartile (1=highest, 4=lowest)
        
  - name: metric_film_performance
    description: Film performance metrics with rankings
    columns:
      - name: film_id
        description: Film identifier
      - name: title
        description: Film title
      - name: rating
        description: Film rating
      - name: rental_rate
        description: Standard rental rate
      - name: rental_duration
        description: Standard rental duration in days
      - name: language_name
        description: Film language
      - name: total_rentals
        description: Total number of rentals
      - name: total_revenue
        description: Total revenue generated
      - name: unique_customers
        description: Number of unique customers
      - name: average_rental_amount
        description: Average rental amount
      - name: revenue_per_rental
        description: Revenue per rental transaction
      - name: popularity_rank
        description: Rank by rental count
      - name: revenue_rank
        description: Rank by total revenue
        
  - name: metric_store_performance
    description: Store performance metrics
    columns:
      - name: store_id
        description: Store identifier
      - name: store_city
        description: Store city
      - name: store_country
        description: Store country
      - name: total_rentals
        description: Total rentals from store
      - name: total_revenue
        description: Total revenue from store
      - name: unique_customers
        description: Unique customers at store
      - name: unique_films_rented
        description: Unique films rented from store
      - name: average_rental_amount
        description: Average rental amount
      - name: revenue_per_customer
        description: Revenue per customer
      - name: revenue_per_rental
        description: Revenue per rental
        
  - name: metric_rolling_trends
    description: Rolling window trend metrics (7-day and 30-day)
    columns:
      - name: date_day
        description: Calendar date
      - name: rentals_rolling_7d
        description: Rolling 7-day rental count
      - name: revenue_rolling_7d
        description: Rolling 7-day revenue
      - name: avg_rental_amount_rolling_7d
        description: Rolling 7-day average rental amount
      - name: rentals_rolling_30d
        description: Rolling 30-day rental count
      - name: revenue_rolling_30d
        description: Rolling 30-day revenue
      - name: avg_rental_amount_rolling_30d
        description: Rolling 30-day average rental amount
