version: 2

models:
  - name: revenue_metrics
    description: >
      Daily revenue metrics aggregated from sales transactions.
      Tracks total revenue, customer count, rental volume, and derived KPIs
      across time dimensions for business performance analysis.
    columns:
      - name: rental_date_key
        description: Foreign key to dim_calendar for the rental date
        tests:
          - not_null
      - name: rental_date
        description: Actual date of the rental transaction
        tests:
          - not_null
      - name: year
        description: Year of the rental transaction
      - name: month
        description: Month of the rental transaction
      - name: quarter
        description: Quarter of the rental transaction
      - name: total_revenue
        description: Sum of all rental amounts for the date
        tests:
          - not_null
      - name: distinct_customers
        description: Count of unique customers who rented on this date
        tests:
          - not_null
      - name: rental_count
        description: Total number of rental transactions on this date
        tests:
          - not_null
      - name: avg_revenue_per_rental
        description: Average revenue amount per rental transaction
      - name: revenue_per_customer
        description: Average revenue generated per distinct customer on this date

  - name: customer_metrics
    description: >
      Customer-level metrics showing lifetime value and engagement patterns.
      Aggregates each customer's rental history, spending behavior, and 
      activity tenure for customer analytics and segmentation.
    columns:
      - name: customer_key
        description: Surrogate key for the customer dimension
        tests:
          - not_null
          - unique
      - name: customer_id
        description: Natural key for the customer
        tests:
          - not_null
      - name: first_name
        description: Customer's first name
      - name: last_name
        description: Customer's last name
      - name: email
        description: Customer's email address
      - name: lifetime_rentals
        description: Total number of rentals by this customer
        tests:
          - not_null
      - name: lifetime_revenue
        description: Total revenue generated by this customer
        tests:
          - not_null
      - name: distinct_films_rented
        description: Count of unique films rented by this customer
        tests:
          - not_null
      - name: avg_rental_amount
        description: Average amount per rental for this customer
      - name: first_rental_date
        description: Date of the customer's first rental
        tests:
          - not_null
      - name: last_rental_date
        description: Date of the customer's most recent rental
        tests:
          - not_null
      - name: customer_tenure_days
        description: Number of days between first and last rental
      - name: revenue_per_rental
        description: Calculated revenue per rental (lifetime_revenue / lifetime_rentals)

  - name: rental_metrics
    description: >
      Film and store-level rental performance metrics.
      Tracks popularity, revenue generation, and customer reach for each
      film-store combination to support inventory and merchandising decisions.
    columns:
      - name: film_id
        description: Primary key for the film
        tests:
          - not_null
      - name: store_id
        description: Primary key for the store
        tests:
          - not_null
      - name: film_title
        description: Title of the film
        tests:
          - not_null
      - name: release_year
        description: Year the film was released
      - name: rental_count
        description: Total number of times this film was rented at this store
        tests:
          - not_null
      - name: distinct_customers
        description: Count of unique customers who rented this film at this store
        tests:
          - not_null
      - name: total_revenue
        description: Total revenue generated from this film at this store
        tests:
          - not_null
      - name: avg_rental_price
        description: Average price per rental for this film at this store
      - name: first_rental_date
        description: Date of the first rental of this film at this store
        tests:
          - not_null
      - name: last_rental_date
        description: Date of the most recent rental of this film at this store
        tests:
          - not_null
      - name: days_in_circulation
        description: Number of days between first and last rental
      - name: revenue_per_rental
        description: Calculated revenue per rental (total_revenue / rental_count)
      - name: customer_diversity_ratio
        description: Ratio of distinct customers to total rentals (measures repeat vs new customer rentals)
