"""
FastAPI application for dbt semantic model serving.

This application provides REST API endpoints to query and serve
semantic models generated by dbt.
"""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from contextlib import asynccontextmanager

from app.routers import semantic_models
from app.core.config import settings


@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Lifespan context manager for startup and shutdown events.
    """
    # Startup
    print("Starting dbt Semantic Model API...")
    yield
    # Shutdown
    print("Shutting down dbt Semantic Model API...")


app = FastAPI(
    title=settings.PROJECT_NAME,
    description="API for serving dbt semantic models",
    version=settings.VERSION,
    root_path=settings.API_V1_STR,
    lifespan=lifespan,
)

# Configure CORS
app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.ALLOWED_ORIGINS,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Include routers
app.include_router(
    semantic_models.router,
    prefix=f"/semantic-models",
    tags=["semantic-models"]
)


@app.get("/")
async def root():
    """Root endpoint """
    return {
        "service": settings.ROOT_NAME,
        "version": settings.VERSION
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(
        "main:app",
        host="0.0.0.0",
        port=8000,
        reload=False
    )
