# version: 2

# models:
#   - name: fact_sales
#     tests:
#       - not_null:
#           column_name: rental_id
#       - unique:
#           column_name: rental_id

#   - name: dim_customer
#     tests:
#       - unique:
#           column_name: customer_key
#       - not_null:
#           column_name: customer_key
